"""empty message

Revision ID: 81b9f97f40b7
Revises: 4c2683e5f249
Create Date: 2019-06-07 13:44:24.864161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81b9f97f40b7'
down_revision = '4c2683e5f249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agenda', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agenda', 'date')
    # ### end Alembic commands ###
